Added tuples deleting by key + cs fix
basis-company/tarantool-admin pull request #73
Opened 2023-12-14 12:09 UTC by Firetawnyowl

2023-12-15 10:54 UTC, nekufa requested changes

2023-12-15 10:54 UTC, nekufa commented on php/Job/Space/Truncate.php
> +    public ?int $indexNumber = null;
лучше по аналогии с select использовать свойство с названием index

2023-12-15 10:54 UTC, nekufa commented on php/Job/Space/Truncate.php
> +    public int $iterator = 0;
лучше по аналогии с select не кодировать числом итератор, а использовать ::ALL свойство

2023-12-15 10:54 UTC, nekufa commented on php/Job/Space/Truncate.php
> +                                        for i = 1, #tuples, 1 do
надо открывать транзакцию чтобы каждая операция не складывалась отдельно в wal лог, после цикла закомитить. заодно если операция приведёт к ошибке, то транзакция откатится полностью

2023-12-15 10:54 UTC, nekufa commented on php/Job/Space/Truncate.php
> +            $this->getClient()->evaluate('tuples = box.space.' . $spaceName . '.index[' . $this->indexNumber . ']:
вместо конкатенации лучше использовать подстановку в строчку, но в данном случае лучше вообще передавать все зависимые данные параметрами evaluate. тогда и preparedKey будет нужен потому что тогда сериализация массива станет задача протокола.
их можно удобно разложить через `local space, index, key, iterator = ...` и соответственно передать в качестве параметров evaluate

2023-12-15 10:54 UTC, nekufa commented on public/admin/js/Database/Spaces.js
> +    if (searchdata == undefined) {
выглядит как будто весь блок searchdata == undefined не нужен, можно при инициализации локальных переменных сразу раскидать туда нужные значения типа spaceParams. по коду везде sendData мы называем params, тут можно их также и использовать. по сути, мы собираем параметры вызова и это их название

2023-12-15 10:54 UTC, nekufa commented on public/admin/js/Database/Spaces.js
> +        sendData = Ext.apply(spaceParams, { key: key, indexNumber: indexNum, iterator: iterator });
если мне не изменяет память, Ext.apply применяет прям к объекту значения, дополнительно возвращает его

2023-12-15 10:54 UTC, nekufa commented on public/admin/js/Space/toolbar/Collection.js
> +      text: 'Delete Tuples',
давай оставим текст truncate по дефолту, но когда производим поиск по индексу - тогда название менять на truncate rows.

2023-12-15 10:54 UTC, nekufa commented on public/admin/js/Database/Spaces.js
> +  truncateSpace(space, searchdata = undefined) {
в searchdata лучше вместо тапла передавать прям объект searchParams = {index: .., key:.., iterator: ..} будет легче читаемость и промежуточные переменные не нужны. возможно даже прийти к Ext.apply(params, searchParams) если всё правильно назвать

2023-12-21 15:19 UTC, litstat commented on php/Job/Admin/Configuration.php
исходный вариант лучше читается

2023-12-21 15:28 UTC, litstat commented on php/Job/Space/Truncate.php
> +                                        tuples = box.space[space].index[index]:
королевские отступы)
может варианты? типа:
```php
$this->getClient()->evaluate(
  'local space, index, key, iterator = ...
  tuples = box.space[space].index[index]:
  ...',
  $space->getName(), 
  $this->index, 
  $key, 
  $this->iterator
);
```

2023-12-21 16:11 UTC, litstat commented on public/admin/js/Database/Spaces.js
> +          break;
```suggestion
  keyEmptyCheck(key) {
    return !key || !key.some(v => v == null);
  }
```

2023-12-21 16:23 UTC, litstat commented on public/admin/js/Database/Spaces.js
> +  truncateSpace(space, searchdata = undefined) {
если из этого метода убрать упоминания `undefined`, то ничего не поменяется, а букв меньше

2023-12-21 16:29 UTC, litstat commented on public/admin/js/Database/Spaces.js
> +    }
try-catch тут лишний.
достаточно `Ext.apply(params, searchdata)`
или `Object.assign(params, searchdata)` [Object.assign](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

а добавить эту строку можно после двух `var` ниже, чтобы код лучше сжимался

2023-12-21 17:07 UTC, litstat commented on public/admin/js/Database/Spaces.js
> +  truncateSpace(space, searchdata = undefined) {
```js
  truncateSpace(space, searchdata) {
    var params = this.spaceParams(space);

    var message =
      'Are you sure to truncate space ' + space + '?<br/>' +
      'This operation can not be undone';

    if (searchdata && searchdata.index) {
      if (!this.keyValidCheck(searchdata.key)) {
        Ext.MessageBox.alert('Warning!', 'Not valid key. Please, fill in all fields starting from the first.');
        return;
      }

      Ext.apply(params, searchdata);

      message = 'Are you sure to delete tuples by index ' +  searchdata.indexObj.name +
                ' and key ' + searchdata.key + ' from space ' + space + '?<br/>' +
                'This operation can not be undone';
    }

    Ext.MessageBox.confirm({
      title: 'Danger!',
      icon: Ext.MessageBox.WARNING,
      message: message,
      buttons: Ext.MessageBox.YESNO,
      callback: (answer) => {
        if (answer == 'yes') {
          dispatch('space.truncate', params)
            .then(() => {
              this.refreshSpaces();
              this.up('database-tab').items.each(item => {
                if (item.params && item.params.space == space) {
                  item.items.each(item => {
                    if (item.xtype == 'space-collection') {
                      item.store.load();
                    }
                  });
                }
              });
            });
        }
      },
    });
  }
```

2023-12-21 17:10 UTC, litstat commented on public/admin/js/Space/toolbar/Collection.js
> +
если свойств много, то они лучше читаются на новой строке:
```js
  var searchdata = {
    key: params.key,
    index: params.index,
    indexObj: index,
    iterator: params.iterator,
  };
```

2023-12-22 08:46 UTC, Firetawnyowl commented on public/admin/js/Database/Spaces.js
> +  truncateSpace(space, searchdata = undefined) {
Насчёт searchdata.index не уверена. Он может быть 0, а это в условии тоже будет false, и условие не будет выполняться. А так не должно быть.

2023-12-22 09:41 UTC, Firetawnyowl commented on php/Job/Admin/Configuration.php
Это не моя прихоть, я прогнала линтером, он ругается на несоответствие стилю, я исправила так чтоб не ругался.

2023-12-22 10:31 UTC, Firetawnyowl commented on public/admin/js/Database/Spaces.js
> +          break;
Ключ должен считаться пустым, если в нём все значения null, а не одно любое.
Тогда так:
  keyEmptyCheck(key) {
    return !key || key.every(v => v == null);
  },

2023-12-22 11:10 UTC, Firetawnyowl commented on public/admin/js/Database/Spaces.js
> +  truncateSpace(space, searchdata = undefined) {
Я про вот эту строчку
   if (searchdata && searchdata.index) {

2023-12-22 12:24 UTC, litstat commented on php/Job/Admin/Configuration.php
например
```php
$contents = '<' . '?php return ' . var_export(compact('tag', 'timestamp'), true) . ';';
file_put_contents($filename, $contents);
```

2023-12-22 12:32 UTC, litstat commented on public/admin/js/Database/Spaces.js
> +  truncateSpace(space, searchdata = undefined) {
если `searchdata.index` должно быть числом, 
то тогда подойдёт сравнение >= 0,
так больше конкретики, чем сравнение с абстрактным `undefined`.
вообще, везде лучше использовать строгое сравнение.
```js
if (searchdata && searchdata.index >= 0) {
```

2023-12-22 14:52 UTC, Firetawnyowl commented on php/Job/Admin/Configuration.php
ок

2023-12-25 16:37 UTC, merged